# ---------- BUILD ----------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build do app desejado
ARG APP_NAME
RUN npx nx build $APP_NAME --configuration=production

# ---------- SERVE ----------
FROM nginx:alpine

ARG APP_NAME

COPY --from=build /app/dist/$APP_NAME/browser /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]